### ISSUE TITLE
feat: add test cases

### ISSUE THREAD

**Issue by swr1bm86** [Developer-DAO/hardhat-fe#3]

**Comment by with-heart** [comment]
By "test cases", do you mean unit/integration tests for `hardhat-fe` itself?

**Comment by swr1bm86** [comment]
@with-heart  yes, exactly! there is common patterns for testing hardhat plugins, more details can be found here https://github.com/NomicFoundation/hardhat/tree/master/packages/hardhat-core/test/fixture-projects
