### ISSUE TITLE
feat: artifacts whitelist

### ISSUE THREAD

**Issue by swr1bm86** [Developer-DAO/hardhat-fe#8]
in order to be compatible with hardhat newer than `v2.8.2`, we need to [add artifacts whitelist](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/internal/artifacts.ts#L51) after generating abi files from fe programs

**Comment by with-heart** [comment]
I don't know what an artifacts whitelist is or does. Can you point me in the right direction?

**Comment by swr1bm86** [comment]
@with-heart sorry for the confusion, the direction is just the link I posted on the first comment, the big map is that

1. after hardhat v2.8.x the compile task will eventually execute an subtask to remove all the obsolete artifacts files https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/builtin-tasks/compile.ts#L1401, `obsolete` means **do not correspond to the current solidity files**, for our plugin, the source file is Fe contract files, so all the artifacts files generated by this plugin will automatically removed after the compile task ran out.
2. to solve this, there is a `whitelist` for obsolete artifacts for skipping the remove process https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/internal/artifacts.ts#L198
3. in order to add our artifacts files to the `whitelist`, we simply call `addValidArtifacts` for the rescue https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/internal/artifacts.ts#L51
