### ISSUE TITLE
fix: handle hardhat config corner case

### ISSUE THREAD

**Issue by swr1bm86** [Developer-DAO/hardhat-fe#9]
should cover the following corner case, when the `fe` config is not null but empty, should also set the default `version` correctly:

```js
module.exports = {
  fe: {
  }
};
```

**Comment by AurelienConte** [comment]
Hi, if you have no problems with this i will take this issue.

**Comment by swr1bm86** [comment]
@AurelienConte  sure, any PR is welcome!

**Comment by AurelienConte** [comment]
Thanks, i already submitted a PR about it (did you see it ?)

**Comment by swr1bm86** [comment]
@AurelienConte thx for the concise solution and the test cases!
